/*
 * Stub <term.h> for the FreeBSD cross-check: the one function the
 * picker asks of it, and the two macros that make the include order
 * matter.
 *
 * The real header is generated by ncurses from
 * contrib/ncurses/include/MKterm.h.awk.in over Caps, which turns
 * every capability name into a lowercase macro -- about 490 of them,
 * each "#define NAME CUR Numbers[n]" over "#define CUR ((TERMTYPE
 * *)(cur_term))->". Two of those names are ordinary C identifiers:
 * columns (Caps:306) and lines (Caps:308), and
 * src/plugins/picker/merge.h has a field named lines. That is why
 * altscreen.c is a file of its own and why its <term.h> comes last,
 * and until the review of 2026-09-11 (B4) this stub declared tigetstr
 * and nothing else -- so the cross check passed on the include order
 * its own comment warns against, which the mac's build rejects.
 *
 * The two macros below stand for all of them in the same shape, so a
 * source that includes this header before a header with a field or a
 * variable named lines or columns fails here, in the cross check, the
 * way it fails on the box. The other 488 are not written out: these
 * are the two names the tree actually collides with, and a new
 * collision is one more line here.
 */
#ifndef ZR_XCHECK_TERM_H
#define	ZR_XCHECK_TERM_H

extern char *tigetstr(const char *);

/*
 * The generated header's own shape: the capability macros expand
 * through cur_term, so each one is a member designator and never a
 * plain identifier. Declaring cur_term as void * is enough for that
 * -- nothing of ours reads a capability through it -- and the cast
 * keeps the expansion a well-formed expression wherever the real one
 * would be.
 */
struct zr_xcheck_termtype {
	short	*Numbers;
};
extern void *cur_term;

#define	ZR_XCHECK_CUR	((struct zr_xcheck_termtype *)(cur_term))->
#define	columns		ZR_XCHECK_CUR Numbers[0]
#define	lines		ZR_XCHECK_CUR Numbers[2]

#endif
